services:
  - type: web
    name: crop-recommendation-system
    env: python
    pythonVersion: 3.11.9
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
